### ISSUE TITLE
When i  python cli_demo.py -w THUDM/WebGLM-2B then error come out

### ISSUE THREAD

**Issue by eu09** [THUDM/WebGLM#55]
Traceback (most recent call last):
  File "/home/WebGLM/cli_demo.py", line 21, in <module>
    for results in webglm.stream_query(question):
  File "/home/WebGLM/model/modeling_webglm.py", line 51, in stream_query
    assert len(f) > 0
AssertionError

**Comment by eu09** [comment]
I check when return result have chinese character ,then it return error.

**Comment by eu09** [comment]
another issue is when I use bing as search engine 

[System] Searching ...
No Bing Result
Traceback (most recent call last):
  File "/home/elohlinux/WebGLM/cli_demo.py", line 21, in <module>
    for results in webglm.stream_query(question):
  File "/home/elohlinux/WebGLM/model/modeling_webglm.py", line 36, in stream_query
    refs = self.ref_retriever.query(question)
  File "/home/elohlinux/WebGLM/model/retriever/__init__.py", line 19, in query
    urls = [result.url for result in search_results]
TypeError: 'NoneType' object is not iterable
