### ISSUE TITLE
在运行web_demo时抛异常，页面一直LOADING，烦请帮忙处理。

### ISSUE THREAD

**Issue by shifengbj** [THUDM/WebGLM#59]
在运行web_demo时（公网情况下 , gradio的server_name已经配置为0.0.0.0）,cli_demo下正常。 报错信息如下：

`To create a public link, set `share=True` in `launch()`.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Task exception was never retrieved
future: <Task finished name='5xpinc8eja9_0' coro=<Queue.process_events() done, defined at /root/miniconda3/envs/webglm_new/lib/python3.9/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['test'], 'event...on_hash': '5xpinc8eja9'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing>
Traceback (most recent call last):
  File "/root/miniconda3/envs/webglm_new/lib/python3.9/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/root/miniconda3/envs/webglm_new/lib/python3.9/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/root/miniconda3/envs/webglm_new/lib/python3.9/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/root/miniconda3/envs/webglm_new/lib/python3.9/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['test'], 'event...on_hash': '5xpinc8eja9'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing`

**Comment by wfwei** [comment]
![image](https://github.com/THUDM/WebGLM/assets/1439753/c7058409-a84b-46f4-9255-24cfd07f42c9)

同样遇到，一直加载不出结果

**Comment by aleeasdas** [comment]
同样遇到，加载到一千秒也不出结果

**Comment by hjandlm** [comment]
同样是这种结果
