### ISSUE TITLE
AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_inputs_for_generation'_

### ISSUE THREAD

**Issue by XiaomuWang** [THUDM/WebGLM#6]
When I run `python web_demo.py` the following problem occurs:

_Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.8/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "web_demo.py", line 49, in query
    for resp in webglm.stream_query(query):
  File "/workspace/wangs/gpt_task/WebGLM/model/modeling_webglm.py", line 46, in stream_query
    inputs = self.tokenizer.build_inputs_for_generation(inputs, max_gen_length=1024)
AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_inputs_for_generation'_

**Comment by XiaomuWang** [comment]
My transformer package version is 4.29.1

**Comment by XiaomuWang** [comment]
![image](https://github.com/THUDM/WebGLM/assets/46257486/7c96673e-1f23-4ed4-9645-e5b0d3217d95)
![image](https://github.com/THUDM/WebGLM/assets/46257486/6131c6aa-6e5c-46da-8099-a6ea3a8ce13b)

![image](https://github.com/THUDM/WebGLM/assets/46257486/91f811cc-40de-4a09-afdb-a2b9b1ba7a95)

**Comment by XiaomuWang** [comment]
This happens in both Chinese and English

**Comment by XiaomuWang** [comment]
But I'm using chatglm-6b, maybe it's because of this error

**Comment by XiaomuWang** [comment]
Using the webglm-2b model, solved
